### ISSUE TITLE
Integrate DougBot 1.0 commands

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot2.0#5]

**Comment by SteamingMutt** [comment]
Dropping support for maintenance-mode, game, and rss, as those commands are rarely used on the live version of 1.3.3

**Comment by Perpetucake** [comment]
I want to find a way to save game. RSS isn't used because of the way it is implemented, but honestly this likely requires a per-interface coding to make it useful for each service (maybe). Might be able to simply be better integrated. Also, no RSS streams are active on the main version of DougleyBot, so idk how you would have gathered data for that :S
